print ("hello dude")
x = input("hello,")
print ("you- hello",x)
a = input ("what is ur name")
print ("hello", a)
y = input(" pc-how are ya doing man")
print (" you-man im feeling",y)
print ("ya man","im feeling great dude")
l = input("type your type of bye")
print ("you-ok man",l)
print ("bye dude - program")